entrypoint: Fix shellcheck warnings & reformat
Use standard 4 space indent instead of 2, and be consistent about it.

Signed-off-by: Joe Groocock <me@frebib.net>

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -4,37 +4,38 @@ if [ -n "$DEBUG" ]; then
     set -x
 fi
 
-if ! find . -mindepth 1 | read; then
-  echo -e "Creating default configs...\n"
-  cp -r /opt/cfx-server-data/* /config
-  RCON_PASS="${RCON_PASSWORD-$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 16)}"
-  sed -i "s/{RCON_PASS}/${RCON_PASS}/g" /config/server.cfg;
-  echo "----------------------------------------------"
-  echo "Your RCON password is set to: ${RCON_PASS}"
-  echo -e "----------------------------------------------\n"
+if ! find . -mindepth 1 | read -r; then
+    echo "Creating default configs..."
+    cp -r /opt/cfx-server-data/* /config
+    RCON_PASS="${RCON_PASSWORD-$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 16)}"
+    sed -i "s/{RCON_PASS}/${RCON_PASS}/g" /config/server.cfg;
+    echo "----------------------------------------------"
+    echo "RCON password is set to: ${RCON_PASS}"
+    echo "----------------------------------------------"
 fi
 
 if [ -z "$NO_ONESYNC" ]; then
-  ONESYNC_ARGS="+set onesync on +set onesync_population true"
+    ONESYNC_ARGS="+set onesync on +set onesync_population true"
 fi
 
 CONFIG_ARGS=
 if [ -z "${NO_DEFAULT_CONFIG}" ]; then
-  CONFIG_ARGS="$CONFIG_ARGS $ONESYNC_ARGS +exec /config/server.cfg"
+    CONFIG_ARGS="$CONFIG_ARGS $ONESYNC_ARGS +exec /config/server.cfg"
 fi
 
 if [ -z "${NO_LICENSE_KEY}" ]; then
-  if [ -z "${LICENCE_KEY}" ]; then
-    echo "Licence key not found in environment, please create one at https://keymaster.fivem.net!"
-    exit 1
-  fi
-  CONFIG_ARGS="$CONFIG_ARGS +set sv_licenseKey ${LICENCE_KEY}"
+    if [ -z "${LICENCE_KEY}" ]; then
+        echo "Licence key not found in environment, please create one at https://keymaster.fivem.net!"
+        exit 1
+    fi
+
+    CONFIG_ARGS="$CONFIG_ARGS +set sv_licenseKey ${LICENCE_KEY}"
 fi
 
-exec /opt/cfx-server/ld-musl-x86_64.so.1  \
-  --library-path "/usr/lib/v8/:/lib/:/usr/lib/" \
-  -- \
-  /opt/cfx-server/FXServer \
-       +set citizen_dir /opt/cfx-server/citizen/ \
-       $CONFIG_ARGS \
-       $*
+exec /opt/cfx-server/ld-musl-x86_64.so.1 \
+    --library-path "/usr/lib/v8/:/lib/:/usr/lib/" \
+    -- \
+    /opt/cfx-server/FXServer \
+        +set citizen_dir /opt/cfx-server/citizen/ \
+        $CONFIG_ARGS \
+        $*
